baseURL:                    https://zihao.me/
canonifyURLs:               false
defaultContentLanguage:     en
enableEmoji:                true
googleAnalytics:            UA-62762041-1
languageCode:               en-us
theme:                      cactus-plus-plus
title:                      Zihao Zhang
hasCJKLanguage:             true

params:
  name: Zihao Zhang
  description: Hacking with Bleeding Edge Technology
  twitter: zzh8829
  enableRSS: true
  disqusShortname: zihaosblog
  enableDisqus: true
  enableGoogleAnalytics: true
  # customCSS:
  # - css/zihao.css
  # home: ""
  # about: ""
  # archive: ""
  # subscribe: ""
  # olderPosts: ""
  # newerPosts: ""
  # readMore: ""
  copyright: Copyright Â© 2017 Zihao Zhang <a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0//">CC BY-NC-SA 4.0</a>
  # aboutAuthor: 'I am so interesting.'
  # tweet: ""
  # share: ""
  # title404: ""
  # subtitle404: ""
  iconFont: font-awesome
  staticPages: About Tags
social:
  linkedin-square: https://linkedin.com/in/zzh8829
  instagram: https://instagram.com/zihaozhang_
  github-square: https://github.com/zzh8829
  facebook-square: https://facebook.com/zihao.pro.zhang
  twitter-square: https://twitter-squareter.com/zzh8829
  youtube-square: https://www.youtube.com/user/zzhist

